### ISSUE TITLE
[iam-group-with-policies] Use for_each for aws_iam_policiy

### ISSUE THREAD

**Issue by awoimbee** [terraform-aws-modules/terraform-aws-iam#136]
Right now, if i add an iam policy at the front of the array `var.custom_group_policy_arns`, everything needs to be recreated !
This could be an issue when I'm updating on of the groups I'm part of.
Why not do something like:
```hcl
resource "aws_iam_group_policy_attachment" "custom_arns" {
  for_each = toset(var.custom_group_policy_arns)

  group      = local.group_name
  policy_arn = each.value
}
```
Instead of:
```hcl
resource "aws_iam_group_policy_attachment" "custom_arns" {
  count = length(var.custom_group_policy_arns)

  group      = local.group_name
  policy_arn = element(var.custom_group_policy_arns, count.index)
}
```

**Comment by antonbabenko** [comment]
There were historical reasons (this module started before Terraform 0.13) and also ideological. Using `count` is bad on stateful resources (eg, aws_iam_access_key) because a user will get a new access/secret key every time it is recreated.

For other types of resources like `aws_iam_group_policy_attachment`, the result of recreation will be identical and it is less of a problem from user's point of view when new item is added or removed from the `var.custom_group_policy_arns`.

I don't think we have immediate plans to rewrite this module to support `for_each` and state migrations for existing users from `count` to `for_each` are still not established.
