### ISSUE TITLE
variable should be list(string)

### ISSUE THREAD

**Issue by lukegAtPaxos** [terraform-aws-modules/terraform-aws-iam#260]
https://github.com/terraform-aws-modules/terraform-aws-iam/blob/be6303e95bdf017fcd8a03137526aaa5dee803c6/modules/iam-role-for-service-accounts-eks/variables.tf#L45

Dont understand why this is a map(string), the only thing being provided is the arn. It makes the module interface appear rough. 

https://github.com/terraform-aws-modules/terraform-aws-iam/blob/be6303e95bdf017fcd8a03137526aaa5dee803c6/modules/iam-role-for-service-accounts-eks/main.tf#L50

this line would become 

```
  for_each = { for _, arn in var.role_policy_arns : arn => arn if var.create_role }
```

**Comment by bryantbiggs** [comment]
This is correct - see https://github.com/terraform-aws-modules/terraform-aws-iam/blob/be6303e95bdf017fcd8a03137526aaa5dee803c6/examples/iam-role-for-service-accounts-eks/main.tf#L42-L45

We used to use `count` which would cause issues when changing out policies earlier in the array passed. We switched to use `for_each = toset(var.role_policy_arns)` but this has the downside that if the policy is not yet created, Terraform will fail due to the key of the map being unknown. So we have changed it to this setup to allow for non-disruptive updates as well as policies that are not yet created. I agree - it would have been nice to use an array of policies but:
- https://github.com/hashicorp/terraform/issues/4149
- https://github.com/hashicorp/terraform/issues/30937
