### ISSUE TITLE
OIDC assume role policy conditions appear to be incorrect

### ISSUE THREAD

**Issue by bvp416** [terraform-aws-modules/terraform-aws-iam#280]
## Description

When using the iam-assumable-role-with-oidc sub module (5.4.0), specifically with Github Actions and AWS, I noticed that my build was failing to authenticate with the following error:

`Couldn't retrieve verification key from your identity provider,  please reference AssumeRoleWithWebIdentity documentation for requirements`

I have previously setup an OIDC provider with the same subject and audience before inside the AWS console successfully. I noticed that the difference appears to be that the `StringLike` condition should be for the subjects and `StringEquals` should be for the audiences.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version:
5.4.0
- Terraform version:
v1.2.7
- Provider version(s):
provider registry.terraform.io/hashicorp/aws v4.31.0
provider registry.terraform.io/hashicorp/tls v4.0.3

## Reproduction Code

This is an example of a correct OIDC role trust policy.

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "",
            "Effect": "Allow",
            "Principal": {
                "Federated": "arn:aws:iam::123456789012:oidc-provider/token.actions.githubusercontent.com"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "StringEquals": {
                    "token.actions.githubusercontent.com:sub": "repo:organization/*:*"
                },
                "StringLike": {
                    "token.actions.githubusercontent.com:aud": "sts.amazonaws.com"
                }
            }
        }
    ]
}
```
I have also tested changing the following lines directly in the module to match the above and got it to work that way as well:
https://github.com/terraform-aws-modules/terraform-aws-iam/blob/v5.4.0/modules/iam-assumable-role-with-oidc/main.tf#L36
https://github.com/terraform-aws-modules/terraform-aws-iam/blob/v5.4.0/modules/iam-assumable-role-with-oidc/main.tf#L56

declaring subjects and audiences in the module

## Expected behavior

ability to authenticate with the OIDC provider

## Actual behavior

authentication fails

### Terminal Output Screenshot(s)

https://imgur.com/HixRoLF

**Comment by nmofonseca** [comment]
Hello @bvp416 ,

I actually came across this today with where I needed to specify some audiences for cross-account access for EKS and the examples don't show all the options so I looked into the module code [main.tf](https://github.com/terraform-aws-modules/terraform-aws-iam/blob/master/modules/iam-assumable-role-with-oidc/main.tf#L53) 

For the subjects you seem to have two options:

oidc_fully_qualified_subjects 
or 
oidc_subjects_with_wildcards

From your example you seem to need the wildcards, so if you use that one it will generate the role with StringLike instead of StringEquals. Is not clear whether that was your problem or not since you didn't provide a snippet of your terraform.

Looking at the code the result you will get using the wildcards option should be:

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "",
            "Effect": "Allow",
            "Principal": {
                "Federated": "arn:aws:iam::123456789012:oidc-provider/token.actions.githubusercontent.com"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "StringLike": {
                    "token.actions.githubusercontent.com:sub": "repo:organization/*:*"
                },
                "StringLike": {
                    "token.actions.githubusercontent.com:aud": "sts.amazonaws.com"
                }
            }
        }
    ]
}
```

However the audiences I am not sure StringLike condition is the right thing to use, from documentation and other examples, audiences always have StringEquals so it is more strict, it still works regardless but is less secure I guess.

@cebidhem  this is just a question: can you provide any input on why oidc_fully_qualified_audiences it's using the StringLike condition instead of StringEquals?

**Comment by cebidhem** [comment]
Hey @nmofonseca,

It's been quite a while since I've done this, but honestly I don't remember any particular reason. As far as I can see this now, this could - even should - be a `StringEquals` condition indeed.

**Comment by cebidhem** [comment]
Sorry @nmofonseca I missed the notification. 

I think you can directly propose a PR to be merged.
