### ISSUE TITLE
Please consider aws-cn region

### ISSUE THREAD

**Issue by cloudbeer** [terraform-aws-modules/terraform-aws-iam#309]
## Description

Error info:

```
│ Error: error creating IAM Policy AmazonEKS_Karpenter_Controller_Policy-20221117072227770700000001: MalformedPolicyDocument: Partition "aws" is not valid for resource "arn:aws:ssm:*:*:parameter/aws/service/*".
│ 	status code: 400, request id: ae153421-4ad8-4352-9400-56f4ae875625
│
│   with module.karpenter_irsa.aws_iam_policy.karpenter_controller[0],
│   on .terraform/modules/karpenter_irsa/modules/iam-role-for-service-accounts-eks/policies.tf line 588, in resource "aws_iam_policy" "karpenter_controller":
│  588: resource "aws_iam_policy" "karpenter_controller" {
```

I changed `arn:aws:ssm:*:*:parameter/aws/service/*` to `arn:aws-cn:ssm:*:*:parameter/aws/service/*`  in ".terraform/modules/karpenter_irsa/modules/iam-role-for-service-accounts-eks/variables.tf", it worked.

**Comment by bryantbiggs** [comment]
this is already supported because it is a variable https://github.com/terraform-aws-modules/terraform-aws-iam/blob/2984b29195ce526226267cd06a517e6bdcd91ccf/modules/iam-role-for-service-accounts-eks/variables.tf#L158

we cannot template variable defaults so we provide some defaults that will work for a broad set of use cases, but since these are IAM policies we need to give users control over locking down access to their level of specificity. for regions that use other partitions, users will need to update the respective variables since the defaults are set for the standard partition
